### ISSUE TITLE
Track playtime on each game

### ISSUE THREAD

**Issue by Coderst1** [Lime3DS/Lime-3DS-Emulator#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A feature to track how many hours and minutes you've been playing on each individual game

### Why would this feature be useful?

Would tell people their total playtime on each game

**Comment by OpenSauce04** [comment]
Sounds like a fine addition to me; We can look into this

**Comment by rtiangha** [comment]
It's been done and I've got it working on my [PabloMK7 fork](https://github.com/rtiangha/bravely-offline-citra/releases). It's in an old [Pull Request](https://web.archive.org/web/20240212144630/https://github.com/citra-emu/citra/pull/7423) that never made it in before the shutdown. It didn't work out of the box so I had to figure what was going on first before figuring out how to fix it. But it could use some testing on Linux and Mac because I don't have access to a machine.

I could look into porting it to Lime3DS if no one else wants to do it and if people are happy with FearlessTobi's proposed solution (it's pretty basic). Since there were four features in that original PR, I was actually thinking of breaking them up into four pieces to make scrutinizing easier.

Looks something like this:
![playtime](https://github.com/Lime3DS/Lime3DS/assets/8913195/b685be5a-195a-4e63-8a43-192c896c0620)

**Comment by OpenSauce04** [comment]
@rtiangha This interface looks pretty much like how I would implement it, so I'm fine with this solution 
If you would be willing to port the PR, I would be more than happy to accept 
I can help with testing on the Linux side, and one of the other maintainers has access to an x86 Mac
