### ISSUE TITLE
Phoenix wright ace attorney needs optimization

### ISSUE THREAD

**Issue by mcoldani** [Lime3DS/Lime-3DS-Emulator#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime 2110

### Description of Issue

The game is too slow 

### Expected Behavior

...

### Reproduction Steps

opening the game

### Log File

[citra_log.txt.old.txt](https://github.com/Lime3DS/Lime3DS/files/15161134/citra_log.txt.old.txt)

### System Configuration

CPU:snapdragon 665
GPU/Driver:
RAM:4gb
OS:android 11

**Comment by BlurrySquire** [comment]
Does the game speed vary? Like is it slower in some areas?

I don't have the game myself so I can't test on my pc or phone.

Could you describe what kind of framerate you get?

I'm wondering if this game has bad performance for lots of people on a variety of hardware. If it does then it might be similar to the situation with Luigi's mansion, but due to a different part of the emulator.

**Comment by mcoldani** [comment]
Hi, the game on the intro is just too slow, i didnt even try to play, its just tooooo slow to even show the screen title

**Comment by OpenSauce04** [comment]
I am closing this issue due to its nondescript nature
