### ISSUE TITLE
A suggestion about credits.

### ISSUE THREAD

**Issue by fight-fly** [Lime3DS/Lime-3DS-Emulator#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

A suggestion about credits.

### Why would this feature be useful?

Thank you for your project.
Co-ahuthor does exist, but it seems that PabloMK7/citra has become one of your upstreams. Suggest adding Credits to your readme or wiki. Don't let Lemonade's foolishness happen to this project.
I think the 3ds simulator should be safe, so you can also add citra-emu/citra in credits.

Lime3ds is good.
Thank you.

**Comment by OpenSauce04** [comment]
Credit is inherently given through the use of commit attribution. Further attribution is not necessary under the GPL.

While I appreciate your concern, Lemonade's faults were a result of mass-scale code plagiarism, whether intentional or otherwise, and are not comparable to our operations. You have nothing to worry about.

**Comment by fight-fly** [comment]
...Well.

It seems that...
it's very very difficult to add some words like these:
### Credits/Thanks/Sister projects
- citra-emu/citra
- PabloMK7/citra
- dynarmic
- sdl
- ...(other)

Although you have benefited from these projects.

Any way, 
thank you.
