### ISSUE TITLE
SPIR-V Optimization unintentionally bumps minimum MacOS version from 11 to 13

### ISSUE THREAD

**Issue by OpenSauce04** [Lime3DS/Lime-3DS-Emulator#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2107-2113

### Description of Issue

The inclusion of SPIR-V optimization has increased the minimum MacOS version due to the SPIR-V Tools package dependency only being built for MacOS 13.0 and onwards.
This is an issue as of the merging of #48

### Expected Behavior

The documented minimum MacOS version to run Lime3DS should be accurate

### Reproduction Steps

Attempt to run Lime3DS on MacOS 11 or 12

### Log File

N/A

### System Configuration

N/A

**Comment by OpenSauce04** [comment]
@rtiangha There appear to be two solutions to this problem: either the minimum version of MacOS is increased from 11 to 13, or SPIR-V Optimization is disabled on MacOS.

This increases the minimum supported MacOS version to a very recent release of the operating system which may not be supported by less recent hardware, so I'm not sure that the marginal gains from SPIR-V Optimization is worth the loss of compatibility.

What is your take on this?

**Comment by rtiangha** [comment]
I don't have a Mac, so I'm trying to understand the issue here since I can't test myself.

My understanding is that:
- If building Lime3DS with all the stock options, if SPIRV-Tools is *not* installed on the build system, the optimizer will not be enabled, it'll spit out a warning during `configure` and the compilation will continue.
- Therefore, if someone is trying to build on Mac 11, then it should just go with no user input needed and it won't have optimization enabled.

Now, I believe Github Actions either uses Mac 13 (x86) or 14 (arm) to build its binaries. At the moment, those build systems have `spirv-tools` installed through `brew`.

Are you saying the generated binaries don't run on Mac 11?

If that's the case, and you want to keep Mac 11 as a minimal requirement, then I (begrudgingly) agree that spirv-opt be disabled for Mac builds, I guess. Logic could be put into `externals/CMakeLists.txt` to `set(ALLOW_EXTERNAL_SPIRV_TOOLS OFF)` if it's a Mac, and `set(ALLOW_EXTERNAL_SPIRV_TOOLS ON)` for everything else. Or, remove `spirv-tools` from the `brew` command in `.github/workflows/build.yml`.

However, has anyone tried a modern Lime3DS binary from the Releases page on Mac 11? I'm just curious as to what error it spits out when launching.

**Comment by OpenSauce04** [comment]
I am very new to the MacOS ecosystem, as I only acquired a machine of my own in the last 2 weeks, however to my knowledge the issue is caused by the SPIR-V Tools library being built specifically for MacOS 13. It seems that MacOS executables and libraries are compiled with a baked-in minimum MacOS version, and if the program is attempted to be run on an older version, a message is displayed in the console which implies that the MacOS version is too old

Below is the resulting error when running on my MacBook Pro, which is running MacOS 11:
```
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/dan/Downloads/lime3ds-2113-macos-universal/./lime3ds-gui.app/Contents/MacOS/../Frameworks/libSPIRV-Tools.dylib (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
```

**Comment by rtiangha** [comment]
Got it.

Last question: Can spirv-tools be installed in Mac 11 through either brew or MacPorts? If so, what happens when you try to run Lime3DS after?

Edit: OK, may not work through brew since that only supports Mac 12. It might through MacPorts though. That said, if that doesn't work, then I vote for removing spirv-tools from the brew command in build.yml. That way, if someone is trying to build on Mac 13+ at home and they do have spirv-tools installed, then they'll get the benefit with no intervention on their end.

Another option is to use a dedicated Mac 11 runner to build a version just for that OS, but Github's public macos-11 runner will no longer be available after June 28, 2024. 

And considering that Apple stopped supporting Mac 11 on Sept 26, 2023, it's worth a conversation on how long dead OSes should be reasonably supported for.

**Comment by OpenSauce04** [comment]
While I am aware that Apple has a significantly faster-paced upgrade cycle for their OS compared to other options, I do still think that compatibility with older versions should be preserved within reason. I don't personally think that the use of SPIR-V Tools is a worthy trade-off, as the benefits are likely not noticeable to an average user.

There will be a time down the line where it is appropriate for the minimum MacOS version to be increased. A more significant change once MacOS 11 is a little older would warrant this, however I do not think this is necessary yet.

> Another option is to use a dedicated Mac 11 runner to build a version just for that OS

It would be beneficial to maintain only a single version for MacOS to avoid any potential user confusion on which version to download. As far as I'm concerned the only options are all or nothing.

Additionally, producing a build for a specific version of the operating system may be interpreted as a commitment to continue maintaining that version indefinitely, which could alienate users down the line.

**Comment by rtiangha** [comment]
Well, I vote for removing spirv-opt from the brew command for MacOS x86 and leave it for arm64. Granted, Mac 12 is the oldest that has arm support, but then again, anyone who has an M1 mac should be able to update to 13 or newer for free, and I assume most will so it shouldn't be that much of an issue.

Should I issue a pull request?

**Comment by OpenSauce04** [comment]
> Should I issue a pull request?

If you're able to handle it I would appreciate it

**Comment by rtiangha** [comment]
OK, I'll need a bit of time. I have a thing to get ready for right now, so hopefully I can get it done when I get back home tonight or by tomorrow afternoon (local time, lol).

**Comment by rtiangha** [comment]
Oh wow, I think I got it on the first try. PR incoming.

**Comment by OpenSauce04** [comment]
Closing for reasons specified in the PR
