### ISSUE TITLE
Allow stretching window content in separate windows layout

### ISSUE THREAD

**Issue by main-rouge** [Lime3DS/Lime-3DS-Emulator#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

adding a setting to stretch image in fullscreen / fit to window

### Why would this feature be useful?

More and more games now have support for 16/9 or widescreen through cheats but the image format is always stuck to original 3DS, having an option to fit to the window in full screen would give access to real widescreen with correct format as long as you have multiple monitors 

Right now the only way to do this is to use a custom layout but it is quite limiting and don't allow for multi monitor support since you can't use the "separate windows" setting with the custom layout format so you're forced to only see 1 screen at a time using F9 to switch screen

**Comment by OpenSauce04** [comment]
I see that the issue here primarily refers to the lack of stretching within the Seperate Windows layout. In order to avoid any new feature being partially redundant due to the existence of custom screen layouts and to allow for more flexibility than just the 16:9 aspect ratio, a configuration option can be added to the Layout section of the settings which specifically handles the Seperate Windows layout

This feature will include checkboxes for stretching the content of both the top and bottom screens to fill the window, and will also contain fields for configuring the size of the black bars on both the horizontal and vertical edges of each screen to still allow a 16:9 display ratio on ultrawide monitors and beyond.
