### ISSUE TITLE
Home menu Crash after Pausing from Software/Games

### ISSUE THREAD

**Issue by Emonconnect24** [Lime3DS/Lime-3DS-Emulator#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2114.1

### Description of Issue

Is happening when After Using Software/Game Then press Home menu To pause software Instanlly Crash whole Emulation Software Even Resetting Emulation Setting Still Don't Work*

### Expected Behavior

Crash When Software Paused

### Reproduction Steps

1.Launch Home menu 
2.Open Any Games/Software 
3.Pause Software by pressing home button
4.Then Instanlly Crash After Getting to home menu

### Log File

[lime3ds_log.txt](https://github.com/user-attachments/files/16009979/lime3ds_log.txt)

### System Configuration

CPU:Unisoc T606
GPU/Driver:Mali G57
RAM:4GB
OS:Android 13

**Comment by zcraftelite9495** [comment]
This happens on many lower end devices, varies between game to game, and can be caused by many other seemingly random factors, at least from my personal expirience. Lime3DS only emulates certain areas of the 3DS' ROM Functions and it isnt actually running the 3DS Firmware, but a simulation of it. Due to this, Lime3DS isn't perfect and the Home Menu software isn't always running in memory (one of the reasons for this is that it may cause game performance issues). However, when running the home menu first and then launching an installed CIA from there, the Home Menu stays in memory (this has been known to cause performance issues), it keeps parts of the Home Menu in memory. However, because the 3DS' Firmware isn't 100% accurately emulated, due to factors currently out of the control of the developers, the utilites (like the theme manager, badge manager, ETC.) are not immediately loaded, which sometimes may cause the Home Menu to fail to load (depending on the memory available to Lime3DS), and thus resulting in a System Crash.

**Comment by Emonconnect24** [comment]
The issue seems like not work with 2115 patch after i resseting Lime3ds setting to default I test with Mii Streetpass and the issue is gone. :)
