### ISSUE TITLE
Concern about copyright notice 

### ISSUE THREAD

**Issue by PabloMK7** [Lime3DS/Lime-3DS-Emulator#306]
### Issue

The following commit changed the copyright notice on every file: https://github.com/Lime3DS/Lime3DS/commit/ba0c9aed049647cd49ba5839391de61cc3852630

This is very concerning, as a general rule of thumb, you cannot add yourself to a copyright notice if you didn't do any changes.

In fact I don't like at all this was done to the artic base code which I did entirely on my own. 

Please reconsider this decision, thank you.

**Comment by OpenSauce04** [comment]
I'm unsure what the best method for handling the copyright header is. Due to changes to the code structure, pretty much every file has been modified or moved to a different location compared to the original Citra source, so it is almost impossible to discern which files have or haven't been modified in a "meaningful" manner since Lime3DS's inception.

The only other reasonable option would be to simply leave the entirety of the code as credited to Citra, which will gradually become increasingly inaccurate as time passes and more and more changes are made, and code will be continuously misattributed. At the time of the commit this felt like a happy medium which maintains credit to the original Citra project while also acknowledging changes made by Lime3DS.

I do see now how this could be considered somewhat problematic for changes that have been pulled in from external forks without the action of the original code author, as such with your changes, which is something I had unfortunately overlooked. I am open to alternatives if you have a better suggestion.

**Comment by PabloMK7** [comment]
Probably the best way to handle this is too start editing the copyright header from now on on every commit/PR every time a file is touched, if you don't want to check for every changed file.

**Comment by OpenSauce04** [comment]
That should be fine in the long term. I will revert the commit for now and figure out a good way of enforcing these updated copyright headers. A CI job that runs on PRs to check changed files perhaps? I'll look into what options there are.

Thanks for voicing your concern.
