### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by Shoegzer** [Lime3DS/Lime-3DS-Emulator#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

33bc972901ec6319993a709bb5c6ab71fc54e1ec

### Description of Issue

Building fails with gcc-14.  Build log includes errors such as the following:

```
/home/testing/Desktop/lime3ds/Lime3DS/externals/fmt/include/fmt/ranges.h:211:49: error: self-comparison always evaluates to true [-Werror=tautological-compare]
  211 |                      integer_sequence<bool, (Is == Is)...>) -> std::true_type;
      |                                              ~~~^~~~~
```

It's possible this is a gcc-14 issue as it requires porting some elements of code, as described [here](https://gcc.gnu.org/gcc-14/porting_to.html).

### Expected Behavior

Building succeeds.

### Reproduction Steps

Using gcc-14, build the project.

### Log File

[lime3ds_build_log.txt](https://github.com/user-attachments/files/16449753/lime3ds_build_log.txt)

### System Configuration

CPU: Intel i7-10870h
GPU/Driver: Nvidia GTX 3070 / 535.183
RAM: 32GB
OS: Linux Mint 22 / kernel 6.8
Compiler: gcc-14.0.1

**Comment by OpenSauce04** [comment]
This issue has been resolved in the upstream `fmt` dependency (https://github.com/fmtlib/fmt/issues/3830), and can be fixed by simply updating the submodule. This will be addressed for 2117.

**Comment by rtiangha** [comment]
There are other gcc-13+ issues with fmt which will also need some changes to Lime3DS (at least, it did on PabloMK7's fork). I'll submit a PR right away; I didn't get the test compile done in time before the last dependency update got merged.

**Comment by Shoegzer** [comment]
@OpenSauce04 Thanks, I build into a clean directory each time, and use `git clone --recursive` which should update the `fmt` submodule?

**Comment by rtiangha** [comment]
That's not going to work. The version of fmt that Lime3DS currently uses is version 10.2.1 and is incompatible with gcc-14. Wait until PR #329 is merged in and then things should be fine.

**Comment by Shoegzer** [comment]
Ah yes, I see.  Actually I tried #329 though, with gcc-14, but that failed too: [lime3ds_build_log.txt](https://github.com/user-attachments/files/16465235/lime3ds_build_log.txt).  Unless you meant that should not be tested before it's merged?

**Comment by OpenSauce04** [comment]
> Actually I tried #329 though, with gcc-14, but that failed too

Looking at the log, this failure seems unrelated to the fmt issue, and the build is instead failing because of Qt depreciation warnings. These were likely introduced in Qt 6.8.0, as I have not seen them before and I am using Qt 6.7.2 on my machine. This is simple to fix and will be addressed for 2117.

Thanks for helping us find all of these!

**Comment by rtiangha** [comment]
Yeah, QT 6.8.0 is still in beta and won't come out officially until around September. But it's good to know what's coming, I suppose. You can try disabling the `-Werror=deprecated-declarations` compilation flag and see if the compilation will complete; otherwise, the latest supported version of QT is 6.7.2 (or 6.7.3 when it comes out in August).
