### ISSUE TITLE
Swap screen position on Android

### ISSUE THREAD

**Issue by SilverGreen93** [Lime3DS/Lime-3DS-Emulator#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Is there any way to swap the screen positions/placements and not locations on Android?
Take this as an example: I am right handed and want the bottom touch screen to be on the right, and to be at full size (fit height), and the top screen to fit in the remaining screen on the left.
I can only get the screens in this position, but with the touchscreen on the left, not on the right. If I use the Swap screens button, now the touch screen does move on the right, but it is in the small corner where the non-touch screen has been before.
I just want to mirror the original layout, with the touchscreen being big, but on the right. Is this possible?

Here is the original layout that I need the screen swapped for:
![Screenshot_2024-08-02-09-23-20-842_io github lime3ds android](https://github.com/user-attachments/assets/87d2a005-50ce-4fb6-b3bd-60438de35d6c)

### Why would this feature be useful?

This would be very useful for right handed people, as the touch screen is closer to the hand.

**Comment by OpenSauce04** [comment]
There seemingly two ways of implementing this feature, and I'm unsure which is more appropriate:
- Implement the large screen ratio setting from the desktop version and allow for numbers smaller than 1.0 to be used
- Implement a "swap large screen" or equivalently named button which appears in the side panel when the large screen layout is used and swaps which of the two screens is large

**Comment by SilverGreen93** [comment]
A "Swap large screen" button sounds better for me, as it is self-explainatory and easy to find/use.

**Comment by DavidRGriswold** [comment]
I don't think "Swap Large Screen" makes it clear that the larger screen will be on the right rather than the left - using "swap screens" already swaps which ones is large and which one is small, just keeps the large one on the left even if it's the bottom screen. "Large Screen Position" with options Left and Right is better, but should we go further?

Right now, the large screen layout is opinionated on all platforms in terms of where the small screen appears. On desktop, it appears at the bottom right. On mobile, it appears at the top right. This is not customizable currently. Extending this request, it is possible that a user with different needs might want the smaller screen to appear on the top left, bottom left, above, or below the large screen. On steam deck, I use a larger top screen with a smaller bottom screen directly below it, for example. 

Taking this into account, I can see two other options that can satisfy this request and also potentially be useful for others. 

(1) Add a setting called "Small Screen Position" with eight options - center right, center left, top right, top left, bottom right, bottom left, above, below - that applies in large screen layout. That would allow OP to choose "top left" combined with "swap screens" to get their desired effect while also enabling many other configs (especially in conjunction with the proportion setting)

(2) Alternatively, just push users with this sort of need to custom layouts, which can of course be customized however they want. Once the custom layout PR is merged in, it will become much easier to use for all users and should satisfy this need. 

I would vote for (2) for now, as tackling (1) is a bigger project; i could do it but it would take q while.

**Comment by OpenSauce04** [comment]
In the long run I think the "Small Screen Position" option is the ideal approach, being the easiest to understand and quickest to configure of the bunch. As this kind of layout customization is something I can see many people wanting, it would be a shame to relegate it to the custom layout setting, which could be time consuming to configure and many users may not bother. The custom layout option is only really supposed to be for niche or personalized layouts.

I would recommend creating a new enhancement issue which describes this functionality which will supersede this issue.
