### ISSUE TITLE
CTGP 7 Doesn't work

### ISSUE THREAD

**Issue by WreckageBrother** [Lime3DS/Lime-3DS-Emulator#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Lime3DS 2107

### Description of Issue

![Screenshot_20240410_015636_Lime3DS](https://github.com/Lime3DS/Lime3DS/assets/155763280/6a4f7d11-1d56-4ad3-b5a6-b7bbc27d5d50)

### Expected Behavior

The game doesn't work

### Reproduction Steps

The game doesn't work

### Log File

[citra_log.txt](https://github.com/Lime3DS/Lime3DS/files/14923325/citra_log.txt)

### System Configuration

Samsung Galaxy M62 
8/128
Exynos 9825
Android 13

**Comment by ayrudev** [comment]
it's a known issue, https://twitter.com/Ctgp7/status/1765059135924740117

**Comment by ayrudev** [comment]
hey there, since none of the devs actually owns MK7 would you be able to test if it has been fixed in the latest version of Lime3DS? (2109)

**Comment by rtiangha** [comment]
2109 won't help since this requires the Mode3 mem plugin loader code that he made and was issued as a Pull Request against vanilla Citra but never made it in before the shutdown. He's since deleted the branch that the request was based off of, however that code has lived in his fork for a while (and he's one of the developers of CTGP 7) so it could probably be considered stable.

That said, I did manage to find the Pull Request on the Wayback Machine. Does anyone want me to port it over here?

**Comment by rtiangha** [comment]
Actually, scratch that. I just tried it, and I don't think the patch by itself is enough to get CTGP to work. Either there's some missing stuff in that archived pull request, or CTGP is hardcoded to look for an app named Citra (or the lack of sleep made me mess up applying it; could be equally as valid).

Edit again: Actually, it works on stock Lemonade too (so forget about it looking for a hard coded executable name), but who knows what other code it took from Pablo's fork; I noticed, for example, it has the multiplayer/Pretendo stuff too but I don't see a specific commit for it. Hmm, now that I think about it, if CTGP has online stuff, maybe it needs the multiplayer/Pretendo stuff too?

Anyway, if anyone wants to try themselves, the mem3 Pull Request can be found here:
https://web.archive.org/web/20240304070204/https://github.com/citra-emu/citra/pull/7464

**Comment by servantoftestator** [comment]
Its kinda hard to backtrack lime3ds's history with how polluted it is with re-branding crap and needless reformatting. So I decided just to diff the repo's and here's what I found, lime3ds is missing some luma ips support, emulation speed change support, in pablomk7/src/core/hle/kernel/svc.cpp there's some strange SystemInfoCitraPlatform:: export that exposes your known operating system to the emulator, in pablomk7/src/core/hle/service/ac/ac.cpp and ac.h and ac_i.cpp there's a huge amount of stubbed hle support for wifi ripped out with ugly hacks; probalby to just make it work :tm:, in pablomk7 there's support for 3ds system specific certs LocalFriendCodeSeedB and  , there's an ugly timer hack in pablomk7/src/core/hle/service/cam/y2r_u.cpp for fifa series of games to make them work, and finally lima3ds still has not ripped out telemetry from the core properly.

pablomk7/src/core/hle/kernel/svc.cpp there's some strange SystemInfoCitraPlatform:: export that exposes your known operating system to the emulator, that's probably what ctgp-7 is using to check if you are using a certain emulator that is approved. That and the http hacks in pablomk7/src/core/hle/service/ac/ac.cpp etc. I'd check you referencing lemonade working rtiangha but the repo no longer exists.

My huge wall of text aside rtiangha, pablomk7 does not have the multiplayer/pretendo stuff it just has hacks to make ctgp work. The correct way to implement this would be to find out how ctgp-7 is detecting its being run in an emulator and close that off, and to fully implement HLE wifi correctly.

**Comment by servantoftestator** [comment]
Also also also here's the luma ips patch to apply to lima3ds https://pastebin.com/v2SRq89g , and the patch for loading unique 3ds specific files probably not required? Here's ctcert https://pastebin.com/HtA99Wjp and here's config options for ctcert and other unused unique files in core, DNMT without writing the frontend for loading them, https://pastebin.com/57y4S8v5 . There's a qt frontend in pablomk7 someone could rip out. All those patches are credit pablomk7, all I did was rebase.

Also also rtiangha that PR you mentioned either didn't make it into pablomk7 or all parts of it got merged in lima3ds and pablomk7. This is what I get for wanting authentic upscaled mario kart without garbage like arctic base.

Please ignore my inane ramblings if you happen to know anything about 3ds emulation, which I don't.

**Comment by rtiangha** [comment]
Yeah, trying to figure out the differences between the forks is a bit of a pain. Heck, none of the forks even have the last five Canary commits since they all forked from the Nightly branch (I've got them on my [personal one](https://github.com/rtiangha/bravely-offline-citra/tree/release) that I'm maintaining for fun/personal use, but some of the functionality has been superseeded by newer code).

Anyway, some of what you found can be traced to actual commits and PRs and could possibly be git cherry-pick'ed. Of course, if one were to do that, they might as well just fork PabloMK7's project and save the pain of porting.

FYI, Lime3DS switched to clang-format-18 while the other forks still use clang-format-15. So you could reformat Lime3DS source to be a bit more diff friendly with the others by running something like

`find src/ -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|c\)' -exec clang-format-15 -i {} \;`

in the root directory (although you probably don't need to do it for hpp and cxx files since it looks like the Citra devs just copy/pasted hpp files and I haven't encountered any cxx).
